.gitignore
pom.xml
src/main/java/org/opencds/cqf/OperationFactory.java
src/main/java/org/opencds/cqf/igtools/IgBundler.java

Added new operation that packages all artifacts contained within an IG (specified in the ig.json) as transaction bundles. This operation should greatly ease the workflow around loading IG artifacts into a FHIR server for testing and improve share-ability.

ImplementationGuide Artifact Packaging Operation

---

src/main/java/org/opencds/cqf/igtools/IGProcessor.java
src/main/java/org/opencds/cqf/library/R4LibraryProcessor.java
src/main/java/org/opencds/cqf/library/STU3LibraryProcessor.java
src/main/java/org/opencds/cqf/library/stu3/LibraryGenerator.java
src/main/java/org/opencds/cqf/library/stu3/LibraryRefresher.java
src/main/java/org/opencds/cqf/utilities/IOUtils.java

- Library refresh was writing out generated library rather than preserving the existing
- Fix generated library-type CodeSystem URL
- Fix bug in Library refresh that was causing Content to be duplicated
- Made dependency bundling recursive
- Fixed bug with library not being generated when it doesn't exist.

Library refresh bug fixes

---

src/main/java/org/opencds/cqf/igtools/IGProcessor.java
src/main/java/org/opencds/cqf/igtools/RefreshIGArgumentProcessor.java
src/main/java/org/opencds/cqf/igtools/RefreshIGParameters.java
src/main/java/org/opencds/cqf/library/R4LibraryProcessor.java
src/main/java/org/opencds/cqf/library/STU3LibraryProcessor.java
src/main/java/org/opencds/cqf/utilities/IGUtils.java

Modifies the way the resource value for relatedArtifacts is generated. 
- Adds the -igrp (IG Resource Path) command argument for RefreshIG
- Loads the Implementation Guide resource and extracts the canonicalBase from its URL
- Passes the IG canonicalBase down to the addRelatedArtifact code
- Related artifact changed to use the canonicalBase along with the "Name" of the CQL library rather than the Library ID for relatedArtifact resource values

Added IG resource path arg; changed relatedArtifact reference

---

src/main/java/org/opencds/cqf/tooling/processor/LibraryProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/MeasureProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/PlanDefinitionProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/R4LibraryProcessor.java
src/main/java/org/opencds/cqf/tooling/utilities/IOUtils.java
src/main/java/org/opencds/cqf/tooling/utilities/ResourceUtils.java

Allows versioning to be turned off and still works without the libraries needing to be named with the version number in them

Fixes ISS #96 - Allows versioning to be turned off and still works

---

src/main/java/org/opencds/cqf/tooling/parameter/RefreshIGParameters.java
src/main/java/org/opencds/cqf/tooling/processor/BaseProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/CqlProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/IGProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/IGTestProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/LibraryProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/R4LibraryProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/STU3LibraryProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/argument/RefreshIGArgumentProcessor.java
src/main/java/org/opencds/cqf/tooling/utilities/IOUtils.java
src/main/java/org/opencds/cqf/tooling/utilities/ResourceUtils.java

.ini file is now required and must contain 'fhir-version' setting with a version number value (e.g., 3.0.2, 4.0.1). 
Updated the BaseProcessor to support dstu3 rather than assuming R4.
Improved error messaging/logging throughout CQL translation and refresh.

Fix baseprocessor stu3 support

---

src/main/java/org/opencds/cqf/tooling/processor/TestCaseProcessor.java

that were being included in the existing transaction bundle that caused an issue. Just checked that resource is not a bundle before adding it for test resources.

Test data was bundling the resource types into transaction bundles 

---

src/main/java/org/opencds/cqf/tooling/processor/STU3LibraryProcessor.java

This resolves a bug in the generation of relatedArtifact references for DSTU3 Libraries when refreshing. Specifically, the STU3LibraryProcessor will no remove the version from relatedArtifact references.

Fix stu3 relatedartifact reference

---

src/main/java/org/opencds/cqf/tooling/Main.java
src/main/java/org/opencds/cqf/tooling/OperationFactory.java
src/main/java/org/opencds/cqf/tooling/operation/ExtractMatBundleOperation.java
src/main/java/org/opencds/cqf/tooling/utilities/BundleUtils.java
src/main/java/org/opencds/cqf/tooling/utilities/ResourceUtils.java

Added a new command line argument for extracting a MAT bundle. Documented in the Main class like other options. Expects an argument to point to where the bundle file is and then extracts out the CQL, Libraries, and Measure. Expects a file structure like exists in ecqm-content-r4 to properly place the files where they belong

Mat extraction

---

pom.xml
src/main/java/org/opencds/cqf/tooling/npm/NpmLibrarySourceProvider.java
src/main/java/org/opencds/cqf/tooling/npm/NpmPackageManager.java
src/main/java/org/opencds/cqf/tooling/processor/CqlProcessor.java

Update org.hl7 dependencies to version 5.2.16
Update org.hl7 dependencies to version 5.2.16, update package names, test
- Github Issue:  #180 

Update org.hl7 dependencies to version 5.2.16

---

src/main/java/org/opencds/cqf/tooling/parameter/RefreshIGParameters.java
src/main/java/org/opencds/cqf/tooling/processor/BaseProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/IGProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/IGTestProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/R4LibraryProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/STU3LibraryProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/argument/RefreshIGArgumentProcessor.java

Restored support for Refreshing given ig-path and root-dir rather than only ig.ini
The IG Refresh operation and supporting infrastructure was modified to support the case that refresh is driven by the IG resource file rather than the ig.ini by passing in the path to the IG resource file (-ig-path) and the root directory of the IG (-root-dir). 

Restored the ability to refresh given ig-path and root-dir.

---

src/main/java/org/opencds/cqf/tooling/operation/BundleResources.java

In BundleResources.java the code to work with output path was using linux/Mac specific path delimiters ("/"). For it to work correctly on a Windows machine it needs to use File.separator. That change has only been made here, but needs to done across the project.
- [X ] Code compiles without errors

Changed linux path "/" to File.separator to be platform independent

---

src/main/java/org/opencds/cqf/tooling/npm/NpmLibrarySourceProvider.java
src/main/java/org/opencds/cqf/tooling/npm/NpmModelInfoProvider.java
src/main/java/org/opencds/cqf/tooling/processor/CqlProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/IGProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/R4LibraryProcessor.java
src/main/java/org/opencds/cqf/tooling/utilities/IGUtils.java

This change allows the providers to resolve a name without a namespace (reporting back the namespace in which resolution occurred if it did). This only matters for well-known models such as FHIR and libraries such as FHIRHelpers that have built-in providers in the translator. Rather than using the built-in providers, this change allows FHIR model info and FHIRHelpers to be resolved from an NPM package and report the correct dependency (even though they aren't resolving from the expected package of org.hl7.fhir.r4.core). There is one namespaceURI override required for FHIR, and that is because model names and uris are 1-to-1.

#207: Added support for well-known model and library resolution

---

src/main/java/org/opencds/cqf/tooling/Operation.java
src/main/java/org/opencds/cqf/tooling/measure/r4/RefreshR4MeasureOperation.java
src/main/java/org/opencds/cqf/tooling/processor/MeasureProcessor.java

Added missing parameter in exception in Operation class, Changed RefreshR4MeasureOperation call to get path for file passed in, added meanigful error if library URL resolution did not work
- [X ] Code compiles without errors

Fixed issues with Measure refreshing

---

src/main/java/org/opencds/cqf/tooling/Main.java
src/main/java/org/opencds/cqf/tooling/operation/BundleResources.java

Add an argument to the BundleResources Operation to allow for specifying an ID for the output Bundle
The BundleResources Operation output Bundle should have an ID property value. This change adds an argument to the command line for specifying what that ID should be.

Added bundleId parameter to BundleResources operation

---

src/main/java/org/opencds/cqf/tooling/library/r4/R4LibraryProcessor.java
src/main/java/org/opencds/cqf/tooling/measure/r4/R4MeasureProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/DataRequirementsProcessor.java

Addresses some minor issues with the data requirements gather

Fixed minor issues with data requirements

---

src/main/java/org/opencds/cqf/tooling/common/r4/CqfmSoftwareSystemHelper.java
src/main/java/org/opencds/cqf/tooling/operation/ExtractMatBundleOperation.java
src/main/java/org/opencds/cqf/tooling/processor/DataRequirementsProcessor.java
src/main/java/org/opencds/cqf/tooling/utilities/BundleUtils.java

logic definitions were causing an exception. Added null checks
Logic definition extensions were causing an exception. Added null checks to avoid that.
- [ X] I've read the contribution guidelines 
- [ X] Code compiles without errors

Refresh exception fix

---

src/main/java/org/opencds/cqf/tooling/measure/MeasureProcessor.java

Measure refresh reporting list to console was erroneously measures failing that were actually refreshing
Changed the code so that it uses the path to the measure for successfully refreshing measures so they will not be in failed list when complete.
- [x ] I've read the contribution guidelines 
- [ x] Code compiles without errors

change measureName to show path so remove works

---

src/main/java/org/opencds/cqf/tooling/measure/MeasureProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/PlanDefinitionProcessor.java
src/main/java/org/opencds/cqf/tooling/utilities/ResourceUtils.java

Primary libraries were not being added to bundle on _refresh, if the ID matched the ID of the corresponding FHIR resource (measure & planDefinition).
ResourceUtils.safeAddResource was modified to add FHIR type to key in hashmap. Corresponding code referring to resources list was also modified to search for "FHIRType-" resourcekey.
- [ X] Code compiles without errors

added fhir type to resources map creation to avoid overwrite

---

src/main/java/org/opencds/cqf/tooling/visitor/ElmOperatorRequirement.java
src/main/java/org/opencds/cqf/tooling/visitor/ElmRequirementsVisitor.java

Fixes the issue by introducing a generic OperatorRequirement that captures expression requirements that otherwise resulted in a generic ElmRequirements list (as the default processing for multi-child elm nodes)

#241: Fixed "cannot cast ElmRequirements to ElmExpressionRequirement"

---

pom.xml
scripts/maintenance.sh
src/test/java/org/opencds/cqf/tooling/utilities/DataRequirementsProcessorTest.java
src/test/java/org/opencds/cqf/tooling/utilities/ECQMCreatorTest.java
src/test/resources/log4j.properties
src/test/resources/logback-test.xml

This PR is a hodge-podge of maintenance items for the tooling:
* Standardizes on TestNG
* Standardizes on slf4j / logback
* You can now configure logging by adding "logback.xml" to your classpath 
* [Logback Configuration](http://logback.qos.ch/manual/configuration.html)
* Upgrades various dependencies
* Adds exclusions to the maintenance script
* Fixes build issues on Maven 3.8.1 by adding appropriate exclusions to the pom for missing dependencies

Tooling maintenance

---

src/main/java/org/opencds/cqf/tooling/library/r4/R4LibraryProcessor.java
src/main/java/org/opencds/cqf/tooling/library/stu3/STU3LibraryProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/IGProcessor.java
src/main/java/org/opencds/cqf/tooling/utilities/IOUtils.java

Currently changes in opioid cql files requires running refresh twice to get into bundles
Currently changes in opioid cql files requires running refresh twice to get those changes into bundles. This fix updates the cachedResources with updated refreshedLibraries (IOUtils) and collects the changed library names and adds them to refreshedResourcesNames for bundling. 
- [ X] Code compiles without errors

fix for requiring 2 refreshes to get changes in plandef into bundles

---

src/test/java/org/opencds/cqf/tooling/operation/RefreshIGOperationTest.java

Fix maven build from editing local files
Copy all files under refreshIG resource and move to target directory
before running refresh to avoid editing local files

HotfixMoveRefreshIGFiles

---

README.md

Added documentation of the release process to the project README

Documented release process for CQF Tooling packages

---

pom.xml
src/main/java/org/opencds/cqf/tooling/library/r4/R4LibraryProcessor.java
src/main/java/org/opencds/cqf/tooling/library/stu3/STU3LibraryProcessor.java
src/main/java/org/opencds/cqf/tooling/measure/r4/R4MeasureProcessor.java
src/main/java/org/opencds/cqf/tooling/npm/LibraryLoader.java
src/main/java/org/opencds/cqf/tooling/npm/NpmPackageManager.java
src/main/java/org/opencds/cqf/tooling/processor/BaseProcessor.java

Update hapi fhir version 5.5.3

---

pom.xml
scripts/deploy.sh
scripts/test.sh

This PR removes the `ci` profile from the build. It was created to save some build time when developing locally, but in practice has created continually support issues and tripped devs up since the behavior on the CI server is slightly different than the local machine unless devs used the `-P ci` argument for mvn.

Remove CI Build Profile

---

src/main/java/org/opencds/cqf/tooling/terminology/EnsureExecutableValueSetOperation.java
src/test/java/org/opencds/cqf/tooling/operation/EnsureExecutableValueSetNaiveTest.java
src/test/resources/org/opencds/cqf/tooling/testfiles/refreshIG/input/vocabulary/valueset/manual/valueset-2.16.840.1.113883.3.117.1.7.1.292.json
src/test/resources/org/opencds/cqf/tooling/testfiles/refreshIG/input/vocabulary/valueset/manual/valueset-2.16.840.1.113883.3.464.1003.122.12.1035.json
src/test/resources/org/opencds/cqf/tooling/testfiles/refreshIG/input/vocabulary/valueset/manual/valueset-2.16.840.1.113883.3.464.1003.122.12.1036.json
src/test/resources/org/opencds/cqf/tooling/testfiles/refreshIG/input/vocabulary/valueset/manual/valueset-2.16.840.1.113883.3.464.1003.198.12.1068.json
src/test/resources/org/opencds/cqf/tooling/testfiles/refreshIG/input/vocabulary/valueset/manual/valueset-2.16.840.1.113883.3.464.1003.198.12.1069.json
src/test/resources/org/opencds/cqf/tooling/testfiles/refreshIG/input/vocabulary/valueset/manual/valueset-2.16.840.1.113883.3.464.1003.198.12.1070.json

Valuesets processed by EnsureExecutableValueSet are expanded outside a terminology server, the naive flag helps prevent the use of potentially incomplete or incorrect terminology in a production setting
- Github Issue: 

Added Naive Parameter to EnsureExecutableValueSet Operation

---

pom.xml
src/main/java/org/opencds/cqf/tooling/fhir/api/FileFhirDal.java
src/main/java/org/opencds/cqf/tooling/fhir/api/FileFhirPlatform.java
src/main/java/org/opencds/cqf/tooling/fhir/api/FileFhirPlatformFactory.java
src/main/java/org/opencds/cqf/tooling/parameter/FileFhirPlatformParameters.java
src/test/java/org/opencds/cqf/tooling/FileFhirDalTest.java
src/test/java/org/opencds/cqf/tooling/fhir/api/FileFhirDalTest.java

File system IO implementation of FhirPlatform pattern from Clinical_Quality_Language
https://github.com/cqframework/clinical_quality_language/tree/master/Src/java/cqf-fhir/src/main/java/org/cqframework/fhir/api

Added FhirDal for File System IO

---

pom.xml
src/main/java/org/opencds/cqf/tooling/measure/r4/CqfMeasure.java
src/main/java/org/opencds/cqf/tooling/measure/stu3/CqfMeasure.java
src/main/java/org/opencds/cqf/tooling/terminology/SpreadsheetHelper.java
src/test/resources/org/opencds/cqf/tooling/testfiles/SpreadsheetToCQLOperation/generated/CQLv151ChangesApplied.cql

Spring-boot jar was replacing main artifact during deployment making classes unaccessible.
Supressed Java 11+ warnings in CQFMeasure classes. I don't believe that class is being used anymore. Happy to remove if that is acceptable.

Spring-boot jar attachment and Java 11+ issues

---

tooling/src/main/java/org/opencds/cqf/tooling/casereporting/transformer/ErsdTransformer.java

eRSD Transformer only propagates the RCTC version to the grouper value sets, not leaves.
eRSD Transformer only propagates the RCTC version to the grouper value sets, not leaves.

Only propagate version to grouping valuesets, not leaves.

---

tooling/src/main/java/org/opencds/cqf/tooling/casereporting/transformer/ErsdTransformer.java

Updates to eRSDTransformer to set experimental element false and strip reference to PlanDefinition from Groupers
Updates to eRSDTransformer to set experimental element false and strip reference to PlanDefinition from Groupers

eRSDTransformer experimental fix, PlanDef reference removal

---

tooling/src/main/java/org/opencds/cqf/tooling/operation/ExtractMatBundleOperation.java

Added code to set the id of the Library and the Measure to the name or publishing reasons
Since for publishing we need the id of the resources to match the canonical added code to ensure that the id gets set during the extraction regardless of how it is set in the bundle

Added code to set the id of the Library and the Measure to the name

---

tooling/src/main/java/org/opencds/cqf/tooling/acceleratorkit/DTProcessor.java
tooling/src/main/java/org/opencds/cqf/tooling/acceleratorkit/Processor.java
tooling/src/main/java/org/opencds/cqf/tooling/common/BaseCqfmSoftwareSystemHelper.java
tooling/src/main/java/org/opencds/cqf/tooling/common/JarEnabledCustomThymeleafNarrativeGenerator.java
tooling/src/main/java/org/opencds/cqf/tooling/cql_generation/drool/DroolCqlGenerator.java
tooling/src/main/java/org/opencds/cqf/tooling/cql_generation/drool/visitor/HtmlFileVisitor.java
tooling/src/main/java/org/opencds/cqf/tooling/dateroller/DataDateRollerOperation.java
tooling/src/main/java/org/opencds/cqf/tooling/fhir/api/FileFhirDal.java
tooling/src/main/java/org/opencds/cqf/tooling/modelinfo/StructureDefinitionToModelInfo.java
tooling/src/main/java/org/opencds/cqf/tooling/operation/BundleResources.java
tooling/src/main/java/org/opencds/cqf/tooling/operation/BundleToResources.java
tooling/src/main/java/org/opencds/cqf/tooling/operation/IgBundler.java
tooling/src/main/java/org/opencds/cqf/tooling/operation/ProfilesToSpreadsheet.java
tooling/src/main/java/org/opencds/cqf/tooling/operation/QICoreElementsToSpreadsheet.java
tooling/src/main/java/org/opencds/cqf/tooling/operation/StructureDefinitionToSpreadsheetBase.java
tooling/src/main/java/org/opencds/cqf/tooling/processor/VmrToFhirProcessor.java
tooling/src/main/java/org/opencds/cqf/tooling/qdm/QdmToQiCore.java
tooling/src/main/java/org/opencds/cqf/tooling/quick/QuickPageGenerator.java
tooling/src/main/java/org/opencds/cqf/tooling/terminology/FlatMultiValueSetGeneratorBase.java
tooling/src/main/java/org/opencds/cqf/tooling/terminology/RCKMSJurisdictionsGenerator.java
tooling/src/main/java/org/opencds/cqf/tooling/terminology/SpreadsheetHelper.java
tooling/src/main/java/org/opencds/cqf/tooling/terminology/SpreadsheetToCQLOperation.java
tooling/src/main/java/org/opencds/cqf/tooling/terminology/VSACValueSetGenerator.java
tooling/src/main/java/org/opencds/cqf/tooling/terminology/distributable/DistributableValueSetGenerator.java
tooling/src/main/java/org/opencds/cqf/tooling/utilities/IOUtils.java
tooling/src/main/java/org/opencds/cqf/tooling/utilities/ResourceUtils.java
tooling/src/test/java/org/opencds/cqf/tooling/utilities/IOUtilsTests.java

Throughout the project "/" is used as a delimiter for file paths. This is specific to Linux/Mac OS. This PR adds a helper method which uses Apache Commons IO FilenameUtils.concat function to build platform independent file paths
Github Issue: https://github.com/cqframework/cqf-tooling/issues/187

Add helper method for platform independent file path building

---

tooling/src/main/java/org/opencds/cqf/tooling/terminology/CodeSystemLookupDictionary.java

Removed comment table which is inconsistent with the actual mappings in the dictionary and as such is unhelpful to users.
Removed unused 'SNOMED CT US Edition' entry from the dictionary.
Github Issue: https://github.com/cqframework/cqf-tooling/issues/93 https://github.com/cqframework/cqf-tooling/issues/94

Remove comments which are inconsistent with actual dictionary & remove unused entry

---

pom.xml
scripts/deploy.sh
scripts/install.sh
scripts/maintenance.sh
scripts/setversion.sh
tooling-cli/pom.xml
tooling-ui/pom.xml
tooling/pom.xml
tooling/src/main/java/org/opencds/cqf/tooling/constants/Api.java
tooling/src/main/java/org/opencds/cqf/tooling/cql_generation/context/ElmContext.java
tooling/src/main/java/org/opencds/cqf/tooling/cql_generation/drool/visitor/ElmToCqlVisitor.java

Updates to the latest CQL release 3.6.0, and updates the cqf-tooling version to 3.1.0

Update to CQL 3.6.0, prep for release 3.1.0

---

.github/workflows/build.yml
.github/workflows/check-pr.yaml
.mvn/jvm.config
codecov.yaml
config/checkstyle.xml
pom.xml
tooling-cli/pom.xml
tooling-ui/pom.xml
tooling/pom.xml
tooling/src/main/java/org/opencds/cqf/tooling/acceleratorkit/ExampleBuilder.java
tooling/src/main/java/org/opencds/cqf/tooling/acceleratorkit/StructureDefinitionElementBindingVisitor.java
tooling/src/main/java/org/opencds/cqf/tooling/acceleratorkit/StructureDefinitionElementVisitor.java
tooling/src/main/java/org/opencds/cqf/tooling/cql_generation/builder/VmrToModelElmBuilder.java
tooling/src/main/java/org/opencds/cqf/tooling/processor/IGTestProcessor.java
tooling/src/main/java/org/opencds/cqf/tooling/quick/QuickPageGenerator.java
tooling/src/main/java/org/opencds/cqf/tooling/terminology/SpreadsheetHelper.java
tooling/src/main/java/org/opencds/cqf/tooling/terminology/VSACValueSetGenerator.java
tooling/src/main/java/org/opencds/cqf/tooling/utilities/R4FHIRUtils.java
tooling/src/main/java/org/opencds/cqf/tooling/utilities/STU3FHIRUtils.java
tooling/src/test/java/org/opencds/cqf/tooling/operation/BundleToResourcesTest.java
tooling/src/test/java/org/opencds/cqf/tooling/operation/BundleToTransactionOperationTest.java
tooling/src/test/java/org/opencds/cqf/tooling/operation/RefreshIGOperationTest.java
tooling/src/test/java/org/opencds/cqf/tooling/qdm/QdmToQiCoreTest.java

Prep for 3.2.0 release

---

tooling/src/main/java/org/opencds/cqf/tooling/operations/dateroller/RollTestDates.java

Migrating to LocalDate for parsing and date arithmetic to avoid Java Date DST quirks

Date Roller Test Fixes

---

tooling/src/main/java/org/opencds/cqf/tooling/modelinfo/ClassInfoBuilder.java

Ensure abstract classes are set to retrievable = false in ModelInfo.
Ensure StructureDefinitions with abstract result in the corresponding ModelInfo class having retrievable = false.
- Github Issue:  https://github.com/cqframework/clinical_quality_language/issues/1392

Ensure abstract classes are set to retrievable = false in ModelInfo.

---

tooling/src/main/java/org/opencds/cqf/tooling/measure/MeasureProcessor.java
tooling/src/main/java/org/opencds/cqf/tooling/measure/MeasureRefreshProcessor.java
tooling/src/main/java/org/opencds/cqf/tooling/measure/r4/R4MeasureProcessor.java
tooling/src/main/java/org/opencds/cqf/tooling/measure/r4/RefreshR4MeasureOperation.java
tooling/src/main/java/org/opencds/cqf/tooling/operation/RefreshGeneratedContentOperation.java
tooling/src/main/java/org/opencds/cqf/tooling/parameter/RefreshIGParameters.java
tooling/src/main/java/org/opencds/cqf/tooling/parameter/RefreshMeasureParameters.java
tooling/src/main/java/org/opencds/cqf/tooling/processor/IGProcessor.java
tooling/src/main/java/org/opencds/cqf/tooling/processor/argument/RefreshIGArgumentProcessor.java

This PR contains the necessary updates to support Measure population-level data requirement processing for the IG refresh operation. The outcome of this update will include contained module definition libraries for each of the Measure.group.population defined in the measure if the appropriate flag is present when invoking the IG refresh operation.
- Updated Refresh IG params to include flag for population level data requirement processing
- Added the population level data requirement processing logic to the MeasureRefreshProcessor
- Tested locally with the NHSN measure repository measures

Added support for population-level data requirement processing to IG refresh measure processor

---

tooling/src/main/java/org/opencds/cqf/tooling/library/LibraryProcessor.java
tooling/src/main/java/org/opencds/cqf/tooling/packaging/Package.java
tooling/src/main/java/org/opencds/cqf/tooling/packaging/PackageMeasures.java
tooling/src/main/java/org/opencds/cqf/tooling/packaging/PackagePlanDefinitions.java
tooling/src/main/java/org/opencds/cqf/tooling/packaging/TestPackage.java
tooling/src/main/java/org/opencds/cqf/tooling/packaging/r4/PackageMeasure.java
tooling/src/main/java/org/opencds/cqf/tooling/packaging/r4/PackagePlanDefinition.java
tooling/src/main/java/org/opencds/cqf/tooling/processor/AbstractBundler.java
tooling/src/main/java/org/opencds/cqf/tooling/processor/CqlProcessor.java
tooling/src/main/java/org/opencds/cqf/tooling/processor/IGBundleProcessor.java
tooling/src/main/java/org/opencds/cqf/tooling/processor/ValueSetsProcessor.java
tooling/src/main/java/org/opencds/cqf/tooling/utilities/BundleUtils.java
tooling/src/main/java/org/opencds/cqf/tooling/utilities/IGUtils.java
tooling/src/main/java/org/opencds/cqf/tooling/utilities/IOUtils.java
tooling/src/main/java/org/opencds/cqf/tooling/utilities/ResourceUtils.java
tooling/src/test/java/org/opencds/cqf/tooling/operation/RefreshIGOperationTest.java

Fixed several issues with packaging step in the refresh operation for PlanDefinition and Measure.
- Just packaging now - removed redundant processing
- Simplified and modularized approach 
- Still some TODO items
- Smarter directory discovery - We really should be using IGRepository here...
- Parallel processing?
- Github Issue:  #559
- Tested locally with opioid IG and ecqm-content-qicore-2025
- Added comments and TODOs as necessary. Could definitely revisit to add JavaDoc

Package fix
