.vscode/launch.json
src/main/java/org/opencds/cqf/igtools/IGProcessor.java
src/main/java/org/opencds/cqf/terminology/ValueSetsProcessor.java
src/main/java/org/opencds/cqf/utilities/IOUtils.java
src/main/java/org/opencds/cqf/utilities/LogUtils.java
src/main/java/org/opencds/cqf/utilities/ResourceUtils.java

fixed missing valueset reporting

added fhir context to all getPaths

---

src/main/java/org/opencds/cqf/terminology/ValueSetsProcessor.java
src/main/java/org/opencds/cqf/utilities/ResourceUtils.java

changed contains comparison to equals

changed id names to url

---

src/main/java/org/opencds/cqf/OperationFactory.java
src/main/java/org/opencds/cqf/terminology/SpreadsheetHelper.java
src/main/java/org/opencds/cqf/terminology/distributable/CommonMetaData.java
src/main/java/org/opencds/cqf/terminology/distributable/DistributableValueSetGenerator.java
src/main/java/org/opencds/cqf/terminology/distributable/DistributableValueSetMeta.java
src/main/java/org/opencds/cqf/terminology/distributable/OrganizationalMetaData.java

Added logic to generate R4 ValueSet resources (that conforms to the distributablevalueset/publishablevalueset profile found in the cqf-recommendations IG) from a spreadsheet template

Distributable/Publishable ValueSet Generator

---

pom.xml
src/main/java/org/opencds/cqf/Main.java

* Rev to version 1.0.4.1
* Embedded version information into jar output

Add version information to the jars

---

src/main/java/org/opencds/cqf/library/stu3/LibraryRefresher.java
src/main/java/org/opencds/cqf/processor/R4LibraryProcessor.java
src/main/java/org/opencds/cqf/processor/STU3LibraryProcessor.java

Refresh only depends-on related artifacts

---

.vscode/launch.json
src/main/java/org/opencds/cqf/library/stu3/LibraryRefresher.java
src/main/java/org/opencds/cqf/processor/IGRefreshProcessor.java
src/main/java/org/opencds/cqf/processor/R4LibraryProcessor.java
src/main/java/org/opencds/cqf/processor/argument/RefreshIGArgumentProcessor.java

Moved setting of arguments to the arguments file
Made requirement for ig configuration file not silent
Added "-library" if version is set
Updated fhir401 for launch

Fixed issue with setting of argument

---

src/main/java/org/opencds/cqf/processor/R4LibraryProcessor.java
src/main/java/org/opencds/cqf/processor/STU3LibraryProcessor.java
src/main/java/org/opencds/cqf/utilities/R4FHIRUtils.java
src/main/java/org/opencds/cqf/utilities/ResourceUtils.java
src/main/java/org/opencds/cqf/utilities/STU3FHIRUtils.java

DataRequirement generation add ValueSetReference (uri) rather than ValueSetString.  Only resolve and refresh 'depends-on' relatedArtifacts.

DataRequirements reference

---

src/main/java/org/opencds/cqf/tooling/acceleratorkit/Processor.java
src/main/java/org/opencds/cqf/tooling/terminology/SpreadsheetHelper.java
src/main/java/org/opencds/cqf/tooling/terminology/VSACValueSetGenerator.java

Protect vsac spreadsheet from lines with hidden characters

Cleanse and trim all cell values

---

pom.xml

Propose 1.3.0 Release Redux

---

src/main/java/org/opencds/cqf/tooling/common/BaseCqfmSoftwareSystemHelper.java
src/main/java/org/opencds/cqf/tooling/common/r4/CqfmSoftwareSystemHelper.java
src/main/java/org/opencds/cqf/tooling/common/stu3/CqfmSoftwareSystemHelper.java
src/main/java/org/opencds/cqf/tooling/operation/TestIGOperation.java
src/main/java/org/opencds/cqf/tooling/processor/IGTestProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/PostBundlesInDirProcessor.java
src/main/java/org/opencds/cqf/tooling/utilities/BundleUtils.java
src/main/java/org/opencds/cqf/tooling/utilities/HttpClientUtils.java

developed/tested against connectathon/fhir401

Modified testIG operation to stamp output artifacts with ruler stamp.

---

src/main/java/org/opencds/cqf/tooling/processor/CqlProcessor.java
src/main/java/org/opencds/cqf/tooling/terminology/GenericValueSetGenerator.java
src/main/java/org/opencds/cqf/tooling/terminology/RCKMSJurisdictionsGenerator.java

…ug in generic valueset generator.

Issue 158 jurisdictions generation fixes

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/code_of_conduct.md
.github/contributing.md
.github/governance.md
.github/pull_request_template.md
.gitignore

Resolves #164 
* Issue templates for bugs and feature requests
* Code of Conduct
* Governance documentation
* PR Template
* Contribution Guidelines

Project documentation

---

src/main/java/org/opencds/cqf/tooling/operation/ExtractMatBundleOperation.java

Changed path handling logic to be platform-independent
- Github Issue:  #141

#141: Fixed issues with Mat bundle extraction on Windows

---

pom.xml

This is to pick up some recent bug fixes.

Updated the org.hl7.fhir.core version to 5.2.20

---

pom.xml
src/main/java/org/opencds/cqf/tooling/Main.java
src/main/java/org/opencds/cqf/tooling/modelinfo/ClassInfoBuilder.java
src/main/java/org/opencds/cqf/tooling/modelinfo/ClassInfoSettings.java
src/main/java/org/opencds/cqf/tooling/modelinfo/StructureDefinitionToModelInfo.java
src/main/java/org/opencds/cqf/tooling/modelinfo/fhir/FHIRClassInfoBuilder.java
src/main/java/org/opencds/cqf/tooling/modelinfo/fhir/FHIRModelInfoBuilder.java
src/main/java/org/opencds/cqf/tooling/npm/NpmModelInfoProvider.java
src/main/java/org/opencds/cqf/tooling/processor/CqlProcessor.java

This PR enhances the modelinfo generation adding support for text descriptions of the elements
- Github Issue:  #52 

Feature 52 modelinfo metadata

---

src/main/java/org/opencds/cqf/tooling/Main.java
src/main/java/org/opencds/cqf/tooling/OperationFactory.java
src/main/java/org/opencds/cqf/tooling/acceleratorkit/DTProcessor.java
src/main/java/org/opencds/cqf/tooling/acceleratorkit/DictionaryElement.java
src/main/java/org/opencds/cqf/tooling/acceleratorkit/Processor.java
src/main/java/org/opencds/cqf/tooling/processor/PlanDefinitionProcessor.java

This PR adds plan definition generation to the tooling
- Github Issue: #182  

Feature 182 plandefinition generator

---

.vscode/launch.json
src/main/java/org/opencds/cqf/tooling/processor/MeasureProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/STU3LibraryProcessor.java
src/main/java/org/opencds/cqf/tooling/utilities/BundleUtils.java
src/main/java/org/opencds/cqf/tooling/utilities/IOUtils.java
src/main/java/org/opencds/cqf/tooling/utilities/LogUtils.java
src/main/java/org/opencds/cqf/tooling/utilities/ResourceUtils.java

This PR fixes a few issues discovered while trying to build a dstu3 IG
- Github Issue:  N/A 

Reviving dstu3 support

---

scripts/maintenance.sh

Just a script that will automatically update the pom when there are new releases.
- Github Issue:  N/A

Add a script to do project maintenance

---

pom.xml

This PR was created automatically based on the maintenance script in this project.

Autogenerated Maintenance PR

---

src/main/java/org/opencds/cqf/tooling/operation/BundleToResources.java

This PR adds an operation to unpack a Bundle of resources
- Github Issue:  N/A 

Adding BundleToResources operation

---

src/main/java/org/opencds/cqf/tooling/terminology/CodeSystemLookupDictionary.java

Updated the codesystem lookup dictionary for the HCPCS Level II CodeSystem following HL7's Terminology Publication.

Updated codesystem lookup dictionary for HCPCS Level II.

---

src/main/java/org/opencds/cqf/tooling/processor/DataRequirementsProcessor.java

Added try-catch's to handle exception "Unknown FHIRAllTypes code 'MedicationStatement'" thrown from org.hl7.fhir.r5-5.3.9.jar
The validationMessage might need to be reworked.
- [ X] Code compiles without errors
- [ X] Tests are created / updated

DataRequirementsProcessor try-catch to handle missing dataType in Parameters and dataReqs

---

src/main/java/org/opencds/cqf/tooling/operation/ExtractMatBundleOperation.java
src/main/java/org/opencds/cqf/tooling/processor/DataRequirementsProcessor.java
src/main/java/org/opencds/cqf/tooling/utilities/BundleUtils.java

JIRA issue CQF-856 - Suppress MAT extract narrative
Added a command line parameter that will toggle MAT narrative expression. Default is true - Suppress narrative.
- [X ] Code compiles without errors

Cqf856 measure narrative suppress

---

pom.xml
src/main/java/org/opencds/cqf/tooling/processor/CqlProcessor.java
src/main/java/org/opencds/cqf/tooling/utilities/ResourceUtils.java

Write out the location of the cql-options if loaded, and that default options are used if not.

Add logging for loading cql-options

---

src/main/java/org/opencds/cqf/tooling/operation/BundleResources.java

Added some helpful error messaging in BundlerResources operation.

---

pom.xml
src/main/java/org/opencds/cqf/tooling/library/stu3/STU3LibraryProcessor.java
src/main/java/org/opencds/cqf/tooling/npm/LibraryLoader.java
src/main/java/org/opencds/cqf/tooling/processor/BaseProcessor.java

This PR updates the hapi and fhir core dependencies to their latest versions. There were some breaking changes in the VersionConverter API. Updates were made as required based on the corresponding updates that were made in the core project, as seen here:
[VersionConverter API Changes](https://github.com/hapifhir/org.hl7.fhir.core/commit/30e45f54eda0ceb8617648b5eedc3c2949094977#diff-62f2af92eb255598d0bb420832e2d837c4d6dfa08055ca5b858e26d21ecd5238L222)

Update hapi and fhir core dependencies

---

pom.xml

Fixes issues with resolving artifacts incorrectly.

Reorder repos, configure hln snapshots correctly

---

src/main/java/org/opencds/cqf/tooling/common/r4/CqfmSoftwareSystemHelper.java
src/main/java/org/opencds/cqf/tooling/common/stu3/CqfmSoftwareSystemHelper.java

Made createSoftwareSystemDevice public

change createSoftwareSystemDevice to public

---

src/main/java/org/opencds/cqf/tooling/processor/BaseProcessor.java
src/main/java/org/opencds/cqf/tooling/processor/DataRequirementsProcessor.java
src/main/java/org/opencds/cqf/tooling/visitor/ElmDataRequirement.java

Updates the toDataRequirement method to output Property references as mustSupport elements in the data requirement

Added mustSupport output based on inferred property references

---

src/main/java/org/opencds/cqf/tooling/acceleratorkit/CanonicalResourceAtlas.java
src/main/java/org/opencds/cqf/tooling/acceleratorkit/CanonicalResourceProvider.java
src/main/java/org/opencds/cqf/tooling/acceleratorkit/DictionaryCode.java
src/main/java/org/opencds/cqf/tooling/acceleratorkit/ExampleBuilder.java
src/main/java/org/opencds/cqf/tooling/acceleratorkit/InMemoryCanonicalResourceProvider.java
src/main/java/org/opencds/cqf/tooling/acceleratorkit/Processor.java
src/main/java/org/opencds/cqf/tooling/acceleratorkit/TestCaseProcessor.java
src/main/java/org/opencds/cqf/tooling/library/LibraryProcessor.java
src/main/java/org/opencds/cqf/tooling/measure/MeasureProcessor.java
src/main/java/org/opencds/cqf/tooling/utilities/IOUtils.java
src/main/java/org/opencds/cqf/tooling/utilities/ResourceUtils.java

Adds test case generation capability to the DAK processor

Feature 286 testcase generator

---

src/test/java/org/opencds/cqf/tooling/operation/GenerateCQLFromDroolOperationIT.java
src/test/java/org/opencds/cqf/tooling/terminology/CMSFlatMultiValueSetGeneratorIT.java
src/test/java/org/opencds/cqf/tooling/utilities/ECQMCreatorIT.java

This reenables ValueSet generation tests now that we have the failsafe plugin added, and moves some long-running tests to integration tests.

Enabled ValueSet generation tests, Make some long running tests integration tests

---

src/main/java/org/opencds/cqf/tooling/terminology/CodeSystemLookupDictionary.java

Updates to the codesystem lookup dictionary.
Updates to the codesystem lookup dictionary for NDC and PYXIS Medication Dispensing Systems.

Updates to codesystem lookup dictionary.

---

README.md
pom.xml

Rev the version.
- [x ] I've read the contribution guidelines 
- [x ] Code compiles without errors
- [x ] Tests are created / updated
- [x ] Documentation is created / updated

Update version to 1.3.2-SNAPSHOT

---

pom.xml

Updated the translator to the latest 1.5.5-SNAPSHOT

Updated translator version to 1.5.5-SNAPSHOT

---

src/test/java/org/opencds/cqf/tooling/RefreshTest.java
src/test/java/org/opencds/cqf/tooling/library/LibraryProcessorTest.java
src/test/java/org/opencds/cqf/tooling/library/r4/R4LibraryProcessorTest.java
src/test/java/org/opencds/cqf/tooling/library/stu3/STU3LibraryProcessorTest.java
src/test/java/org/opencds/cqf/tooling/measure/r4/R4MeasureProcessorTest.java
src/test/java/org/opencds/cqf/tooling/measure/r4/RefreshR4MeasureOperationTest.java
src/test/java/org/opencds/cqf/tooling/measure/stu3/RefreshStu3MeasureOperationTest.java
src/test/java/org/opencds/cqf/tooling/processor/IGProcessorTest.java

Fix static path clearing between tests
Fix errors in build by adding resourcePath and devicePath clearing in each @BeforeMethod in tests

Hot fix cqf tooling extension error

---

pom.xml
src/main/java/org/opencds/cqf/tooling/vmrToFhir/VmrToFhirTransformer.java

This PR removes the compile-time cql-engine dependency and scopes it to test only. The motivation behind this are breaking changes in the cql-engine that we do not yet want to propagate to downstream projects.

Remove compile-time engine dependency

---

README.md
pom.xml

Prep for release 1.4.0

---

pom.xml
scripts/setversion.sh

Update to next dev version 1.4.1-SNAPSHOT

Rev to version 1.4.1-SNAPSHOT post release

---

pom.xml

Updated the version of the translator to 1.5.7-SNAPSHOT

---

src/main/java/org/opencds/cqf/tooling/library/LibraryProcessor.java

…th alphanumeric
- Github Issue:  (https://github.com/cqframework/cqf-tooling/issues/350)

Remove "library" prefix when fhir library created

---

pom.xml
src/test/java/org/opencds/cqf/tooling/common/BaseCqfmSoftwareSystemHelperTest.java

Junit testing for BaseCqfmSoftwareSystemHelper
- [] Documentation is created / updated

adding test for BaseCqfmSoftwareSystemHelper

---

pom.xml

update to 1.4.2-SNAPSHOT

---

pom.xml

Release 1.4.2

---

pom.xml
src/main/java/org/opencds/cqf/tooling/cql_generation/context/ElmContext.java

Release 1.4.3

---

pom.xml

Release 1.4.4-SNAPSHOT

---

pom.xml
src/test/resources/org/opencds/cqf/tooling/testfiles/SpreadsheetToCQLOperation/generated/CQLv151ChangesApplied.cql

Release 1.4.4

---

pom.xml
src/test/resources/org/opencds/cqf/tooling/testfiles/SpreadsheetToCQLOperation/generated/CQLv151ChangesApplied.cql

Release 1.4.5 snapshot

---

src/main/java/org/opencds/cqf/tooling/terminology/CodeSystemLookupDictionary.java
src/test/resources/org/opencds/cqf/tooling/testfiles/SpreadsheetToCQLOperation/generated/CQLv151ChangesApplied.cql

Corrected HSLOC and CDCREC system URLs and added PresentOnAdmission #173

---

.vscode/launch.json
pom.xml
tooling-cli/pom.xml
tooling/pom.xml
tooling/src/main/java/org/opencds/cqf/tooling/dateroller/README.md

release 2.0.0 updates

---

pom.xml
tooling-cli/pom.xml
tooling/pom.xml
tooling/src/test/java/org/opencds/cqf/tooling/utilities/ECQMCreatorIT.java

found a bug with Datarequirements test, Bryn suggested we comment out and address later: https://github.com/orgs/cqframework/projects/1/views/1?pane=issue&itemId=19013241

V2.2.0 release

---

pom.xml
tooling-cli/pom.xml
tooling/pom.xml

snapshot v2.3.0-SNAPSHOT

---

pom.xml
tooling-cli/pom.xml
tooling/pom.xml

release tooling 2.6.0

---

pom.xml
tooling-cli/pom.xml
tooling/pom.xml

setting up snapshot 2.4.0

---

tooling-cli/src/main/java/org/opencds/cqf/tooling/cli/Main.java
tooling/src/main/java/org/opencds/cqf/tooling/measure/MeasureProcessor.java
tooling/src/main/java/org/opencds/cqf/tooling/operation/RefreshGeneratedContentOperation.java
tooling/src/main/java/org/opencds/cqf/tooling/parameter/RefreshIGParameters.java
tooling/src/main/java/org/opencds/cqf/tooling/processor/IGBundleProcessor.java
tooling/src/main/java/org/opencds/cqf/tooling/processor/IGProcessor.java
tooling/src/main/java/org/opencds/cqf/tooling/processor/PlanDefinitionProcessor.java
tooling/src/main/java/org/opencds/cqf/tooling/processor/TestCaseProcessor.java
tooling/src/main/java/org/opencds/cqf/tooling/processor/argument/RefreshIGArgumentProcessor.java
tooling/src/main/java/org/opencds/cqf/tooling/questionnaire/QuestionnaireProcessor.java
tooling/src/main/java/org/opencds/cqf/tooling/utilities/BundleUtils.java
tooling/src/test/java/org/opencds/cqf/tooling/operation/RefreshIGOperationTest.java
tooling/src/test/java/org/opencds/cqf/tooling/processor/IGProcessorTest.java
tooling/src/test/java/org/opencds/cqf/tooling/questionnaire/QuestionnaireProcessorTest.java

Add bundle timestamp by default. And have a param to control that in `RefreshIG` command

add param for adding timestamp to refresh bundle

---

tooling/src/main/java/org/opencds/cqf/tooling/dateroller/HookDataDateRoller.java
tooling/src/test/resources/org/opencds/cqf/tooling/operation/dateRoller/request-example-rec-01-in-outpatient-opioid.json

**Date Roller update to remove legacy formatting requirements**
- Improved conditional checks to avoid NPE
- Added test without the legacy response/resource format
- Validated locally with changes made in [Opioid IG](https://github.com/cqframework/opioid-cds-r4/pull/308) 
- Github Issue:  #408

Date Roller update to remove legacy formatting requirements

---

pom.xml
tooling-cli/pom.xml
tooling/pom.xml

updating tooling to 2.4.0 release

V2.4.0 release

---

pom.xml
tooling/src/main/java/org/opencds/cqf/tooling/library/LibraryProcessor.java

add default library type as logic library

---

tooling/src/main/java/org/opencds/cqf/tooling/casereporting/transformer/ErsdTransformer.java
tooling/src/test/java/org/opencds/cqf/tooling/casereporting/transformer/ErsdTransformerIT.java
tooling/src/test/resources/casereporting/transformer/eRSDv2PlanDefinition/README.md
tooling/src/test/resources/casereporting/transformer/eRSDv2PlanDefinition/plandefinition-us-ecr-specification.json
tooling/src/test/resources/casereporting/transformer/eRSDv2PlanDefinition/plandefinition-us-ecr-specification.xml

Updates to the eRSD PlanDefinitions. Also removed ReadMe as this repo is no longer source of truth for those.
The eRSD PlanDefinition are updated and strictly for testing no - this repo is no longer the source of truth for them.

Updated the ersd plandefinitions

---

tooling/src/main/java/org/opencds/cqf/tooling/acceleratorkit/CanonicalResourceAtlas.java
tooling/src/main/java/org/opencds/cqf/tooling/acceleratorkit/ExampleBuilder.java
tooling/src/main/java/org/opencds/cqf/tooling/acceleratorkit/Processor.java

Minor bug fixes picked from the AK branch

First slice AK HIV changes

---

tooling/src/test/java/org/opencds/cqf/tooling/acceleratorkit/BaseContentTest.java

Attempting to fix the build I broke.

Force creation of output directory

---

.vscode/settings.json
pom.xml
tooling-cli/pom.xml
tooling-ui/pom.xml
tooling/pom.xml
tooling/src/main/java/org/opencds/cqf/tooling/acceleratorkit/Processor.java
tooling/src/main/java/org/opencds/cqf/tooling/cql_generation/drool/DroolCqlGenerator.java
tooling/src/main/java/org/opencds/cqf/tooling/cql_generation/drool/serialization/Serializer.java
tooling/src/main/java/org/opencds/cqf/tooling/modelinfo/StructureDefinitionToModelInfo.java
tooling/src/main/java/org/opencds/cqf/tooling/npm/NpmModelInfoProvider.java
tooling/src/main/java/org/opencds/cqf/tooling/operations/acceleratorkit/ProcessAcceleratorKit.java
tooling/src/main/java/org/opencds/cqf/tooling/operations/bundle/BundleResources.java
tooling/src/main/java/org/opencds/cqf/tooling/operations/bundle/BundleToResources.java
tooling/src/main/java/org/opencds/cqf/tooling/operations/bundle/BundleTransaction.java
tooling/src/main/java/org/opencds/cqf/tooling/processor/TestCaseProcessor.java
tooling/src/main/java/org/opencds/cqf/tooling/processor/VmrToFhirProcessor.java
tooling/src/test/java/org/opencds/cqf/tooling/operation/VmrToFhirOperationTest.java

* Rev to 3.0.0
* HAPI 6.10.0
* CQL 3.5.0
* JavaX -> Jarkarta

Rev to 3.0.0, Javax -> Jakarta

---

.vscode/settings.json
tooling/src/main/java/org/opencds/cqf/tooling/library/LibraryProcessor.java
tooling/src/test/java/org/opencds/cqf/tooling/library/cqloptions/CqlOptionsLibraryProcessorTest.java
tooling/src/test/resources/org/opencds/cqf/tooling/cqloptions/ig.ini
tooling/src/test/resources/org/opencds/cqf/tooling/cqloptions/input/cql/Test.cql
tooling/src/test/resources/org/opencds/cqf/tooling/cqloptions/input/cql/cql-options.json
tooling/src/test/resources/org/opencds/cqf/tooling/cqloptions/input/options.xml
tooling/src/test/resources/org/opencds/cqf/tooling/cqloptions/input/resources/library/library-Test.json

…ments
Resolves #508 
- [] Documentation is created / updated

Fix cql-options formats being ignored for Library generation

---

.vscode/settings.json
tooling/src/main/java/org/opencds/cqf/tooling/acceleratorkit/Processor.java
tooling/src/test/java/org/opencds/cqf/tooling/acceleratorkit/DTRContentTest.java

DataElement and ContactDataElements fix.
Added dynamique library pick based on the profile
TODO: how to pick the right context. How to switch to the right library for DataElements. Added tests
**Description** : PR to fix acceleratorKit bugs. CQL files generation if mostly fixed. We need to define the proper factor to pick the context and the library.
DataElement and ContactDataElements fix.
Added dynamique library pick based on the profile
TODO: how to pick the right context. How to switch to the right library for DataElements. Added tests
- Github Issue:  https://github.com/alphora/KALM/issues/62 https://github.com/alphora/KALM/issues/64 https://github.com/alphora/KALM/issues/21 https://github.com/alphora/KALM/issues/24
- [ x] I've read the contribution guidelines 
- [ x] Code compiles …

KALM [BUG] AcceleratorKit Bugs

---

tooling/src/main/java/org/opencds/cqf/tooling/processor/CqlProcessor.java

Fix a bug found during connectathon May 2025

Fix bug where only direct deps should be in the refreshed library

---

.github/workflows/build.yml
pom.xml
tooling-cli/pom.xml
tooling-ui/pom.xml
tooling/pom.xml

updates to support new maven central repos

---

pom.xml
tooling-cli/pom.xml
tooling-ui/pom.xml
tooling/pom.xml

adds maven central required name attributes

---

pom.xml

sets jakarta.activation-api version
